---
env: production # to enable google analytics, opengraph, twitter-cards and schema.
description: "ExampleSite description"
keywords: [Blog, Portfolio, PaperMod]
author: Xander Lammertink

images: ["xander.jpg"]
DateFormat: "January 2, 2006"
defaultTheme: auto # dark, light
disableThemeToggle: false

ShowReadingTime: true
ShowShareButtons: true
ShareButtons: ["twitter", "linkedin", "reddit", "whatsapp", "telegram"]
ShowPostNavLinks: true
# ShowBreadCrumbs: true
ShowBreadCrumbs: false
ShowCodeCopyButtons: false
ShowWordCount: true
ShowRssButtonInSectionTermList: true
# UseHugoToc: true
UseHugoToc: false
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: true
tocopen: false

assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: "<link / abs url>"
  favicon16x16: "<link / abs url>"
  favicon32x32: "<link / abs url>"
  apple_touch_icon: "<link / abs url>"
  safari_pinned_tab: "<link / abs url>"

label:
  text: "Home"
  icon: /apple-touch-icon.png
  iconHeight: 35

# profile-mode
profileMode:
  enabled: true
  title: "Xander Lammertink"
#  subtitle: "This is subtitle"
  imageUrl: "xander.jpg"
  imageWidth: 240
  imageHeight: 240
  imageTitle: "Xander Lammertink"
  buttons:
    - name: Posts
      url: posts
    - name: Topics
      url: tags

# home-info mode
#homeInfoParams:
#  Title: "Hi there \U0001F44B"
#  Content: Welcome to my blog

socialIcons:
  - name: linkedin
    url: "https://www.linkedin.com/in/xander-lammertink"
  - name: github
    url: "https://github.com/xlammertink"

#analytics:
#  google:
#    SiteVerificationTag: "XYZabc"
#  bing:
#    SiteVerificationTag: "XYZabc"
#  yandex:
#    SiteVerificationTag: "XYZabc"

cover:
  hidden: true # hide everywhere but not in structured data
  hiddenInList: true # hide on list pages and home
  hiddenInSingle: true # hide on single page

#editPost:
#  URL: "https://github.com/<path_to_repo>/content"
#  Text: "Suggest Changes" # edit text
#  appendFilePath: true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]
